
CREATE Table CURSO(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DESCRIPCION VARCHAR(255)
);


CREATE TABLE ESTUDIANTE(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    CORREO VARCHAR(255),
    EDAD INTEGER,
    FECHA_NACIMIENTO DATE,
    ID_CURSO INTEGER,
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID)
);

CREATE TABLE MATRICULA(
    ID SERIAL PRIMARY KEY,
    FECHA_MATRICULA DATE,
    ID_ESTUDIANTE INTEGER UNIQUE,
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID)    
);

CREATE TABLE PROFESOR(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    CORREO VARCHAR(255) UNIQUE,
    EDAD INTEGER,
    FECHA_NACIMIENTO DATE,
    ID_CURSO
);

CREATE TABLE PROFESOR_CURSO(
    ID_PROFESOR INTEGER,
    ID_CURSO INTEGER,
    PRIMARY KEY (ID_PROFESOR, ID_CURSO),
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID)
);